export const VIEW_INCREMENT = 'VIEW_INCREMENT'
export const VIEW_DECREMENT = 'VIEW_DECREMENT'
export const TASK_UPDATE = "TASK_UPDATE"
export const TASK_INSERT = "TASK_INSERT"
export const TASK_DELETE = "TASK_DELETE"
