export const TASK_UPDATE = "TASK_UPDATE"
export const TASK_INSERT = "TASK_INSERT"
export const TASK_DELETE = "TASK_DELETE"
    // export const DELETE_FLAG_SET = "DELETE_FLAG_SET"
    // export const DELETE_FLAG_BREAK = "DELETE_FLAG_BREAK"